language: python
dist: trusty
sudo: required
notifications:
  email: false
python:
- '3.5'
before_install:
- pip install tox
- pip install python-coveralls
script:
- tox
deploy:
  provider: pypi
  user: petersinghanburaj
  distributions: sdist
  password:
    secure: JECBiSUPBEYFi+9u0jMJzhrAMPkI77Pvb77ax8GCZrllFNxD4vhy7Xrpk+yIqHmqp7mCxKglwHoVBPhpEPPir241uX8MVtPVfuyywOr8WAS+a6egZZ0Xp9JaNV84rVe3MaRKjFm5OqTIZXkg56rYz+ZI5yBCZoWYVKFoz9D/CHxx+JExHkwV7lLkgyqJzXe4M9o4V1c9p9Qp+SuqHWLW7ZeD2fEomc3BYFePAP3ynMoDxmrGZT1eskekz+O4DJCwzHwVYb98bwN8kHy71IetcIyoxUReEhAyayzhXV+bzbEW3Qsl/GfXB+cNc3w/QJ8/jVz6L0V5az7sSl9bNRdxlAe55b0EvNd4J7gaVv8rpsKNzqIh6ppwAhOHh24mw9puDrfvHWe7Ls8xRyx0Z+UcU1UwMm/JdT4YQbiRcSMN37BaXkp2xTesHpcFPW5UfBdZu6jauPjlDI3DaT+Xxlr6Glsm9rn5xho+0B5gce55tnjCT7p8b4V7/Jra2GujFh7kBaqB6bV3yLmeqghXC+sAtUSU8nSK4QT6pwmHzZgJAYOYQk5lTH0vMgP04k6jx4zgD+TMXgtKRaM1RGmvH6eqetcQLgeMnW4324o4MNn9jk+c8dr59ZJRfzU6emv1PEO4pWX1HS0BMNw8DUJoe3k9R/SQSsd3yMuozi1QRpfLo6Y=
  on:
    branch: master
after_success:
- coveralls
